### ISSUE TITLE
cumbersome when region::protect deals with Elf64_Phdr.p_flags

### ISSUE THREAD

**Issue by 0xF0CACC1A** [darfink/region-rs#28]
I need to protect the content of one segment in memory with its protection flags. So far I managed in this way
```
            unsafe {
                region::protect(
                    ph.p_vaddr as *const u8,
                    ph.p_memsz.try_into().unwrap(),
                    flags_to_prot(ph.p_flags),
                )
                .unwrap();
            }
```
...
```
fn flags_to_prot(mut flags: u32) -> region::Protection {
    let mut prot = region::Protection::NONE;
    [4, 2, 1].iter().for_each(|e| {
        if flags >= *e {
            match e {
                4 => prot |= Protection::READ,
                2 => prot |= Protection::WRITE,
                1 => prot |= Protection::EXECUTE,
                _ => prot |= Protection::NONE,
            }
            flags -= e;
        }
    });
    prot
}

```
I was wondering why the library doesn't provide any method to turn u32 value into a region::Protection value

**Comment by darfink** [comment]
Doesn't [Protection::from_bits_truncate](https://docs.rs/region/latest/region/struct.Protection.html#method.from_bits_truncate) cover your use case?

**Comment by darfink** [comment]
I realize the above won't work for the current release.

I had always intended for the protection flags to correspond to their UNIX constants, but I discovered today that that has not been the case. Although not problematic, since they've always been explicitly mapped to their native counterparts, it prevented `from_bits_*` to works as expected. Fix pushed as [03fd93c](https://github.com/darfink/region-rs/commit/03fd93c3ae23e197775576a4fe170d29f4e06ffc).

**Comment by darfink** [comment]
Fixed with version [3.0.1](https://crates.io/crates/region/3.0.1).

**Comment by 0xF0CACC1A** [comment]
the patch didn't fix the problem
![image](https://github.com/darfink/region-rs/assets/162066417/80c5edc6-6cc1-4bd7-997b-a1c1fa3a5435)
```
load_phdrs_iter
        .clone()
        .filter(|ph| ph.p_memsz > 0)
        .for_each(|ph| unsafe {
            println!(
                "{}, {}, {}",
                ph.p_flags,
                flags_to_prot(ph.p_flags),
                Protection::from_bits_truncate(ph.p_flags.try_into().unwrap())
            );
```
```
fn flags_to_prot(mut p_flags: u32) -> region::Protection {
    [4, 2, 1].iter().fold(Protection::NONE, |mut acc, x| {
        if p_flags >= *x {
            match x {
                4 => acc |= Protection::READ,
                2 => acc |= Protection::WRITE,
                1 => acc |= Protection::EXECUTE,
                _ => acc |= Protection::NONE,
            }
            p_flags -= x;
        }
        acc
    })
}
```
